export interface DailyVerse {
  reference: string;
  text: string;
}

export const DAILY_VERSES: DailyVerse[] = [
  { reference: "Genesis 1:1", text: "In the beginning God created the heaven and the earth." },
  { reference: "Genesis 1:27", text: "So God created man in his own image, in the image of God created he him; male and female created he them." },
  { reference: "Genesis 2:24", text: "Therefore shall a man leave his father and his mother, and shall cleave unto his wife: and they shall be one flesh." },
  { reference: "Genesis 9:13", text: "I do set my bow in the cloud, and it shall be for a token of a covenant between me and the earth." },
  { reference: "Genesis 12:2", text: "And I will make of thee a great nation, and I will bless thee, and make thy name great; and thou shalt be a blessing:" },
  { reference: "Genesis 28:15", text: "And, behold, I am with thee, and will keep thee in all places whither thou goest, and will bring thee again into this land; for I will not leave thee, until I have done that which I have spoken to thee of." },
  { reference: "Genesis 50:20", text: "But as for you, ye thought evil against me; but God meant it unto good, to bring to pass, as it is this day, to save much people alive." },
  { reference: "Exodus 14:14", text: "The LORD shall fight for you, and ye shall hold your peace." },
  { reference: "Exodus 15:2", text: "The LORD is my strength and song, and he is become my salvation: he is my God, and I will prepare him an habitation; my father's God, and I will exalt him." },
  { reference: "Exodus 20:12", text: "Honour thy father and thy mother: that thy days may be long upon the land which the LORD thy God giveth thee." },
  { reference: "Exodus 33:14", text: "And he said, My presence shall go with thee, and I will give thee rest." },
  { reference: "Leviticus 19:18", text: "Thou shalt not avenge, nor bear any grudge against the children of thy people, but thou shalt love thy neighbour as thyself: I am the LORD." },
  { reference: "Numbers 6:24", text: "The LORD bless thee, and keep thee:" },
  { reference: "Numbers 6:25", text: "The LORD make his face shine upon thee, and be gracious unto thee:" },
  { reference: "Numbers 6:26", text: "The LORD lift up his countenance upon thee, and give thee peace." },
  { reference: "Numbers 23:19", text: "God is not a man, that he should lie; neither the son of man, that he should repent: hath he said, and shall he not do it? or hath he spoken, and shall he not make it good?" },
  { reference: "Deuteronomy 6:5", text: "And thou shalt love the LORD thy God with all thine heart, and with all thy soul, and with all thy might." },
  { reference: "Deuteronomy 31:6", text: "Be strong and of a good courage, fear not, nor be afraid of them: for the LORD thy God, he it is that doth go with thee; he will not fail thee, nor forsake thee." },
  { reference: "Deuteronomy 31:8", text: "And the LORD, he it is that doth go before thee; he will be with thee, he will not fail thee, neither forsake thee: fear not, neither be dismayed." },
  { reference: "Deuteronomy 33:27", text: "The eternal God is thy refuge, and underneath are the everlasting arms: and he shall thrust out the enemy from before thee; and shall say, Destroy them." },
  { reference: "Joshua 1:9", text: "Have not I commanded thee? Be strong and of a good courage; be not afraid, neither be thou dismayed: for the LORD thy God is with thee whithersoever thou goest." },
  { reference: "Joshua 24:15", text: "And if it seem evil unto you to serve the LORD, choose you this day whom ye will serve; whether the gods which your fathers served that were on the other side of the flood, or the gods of the Amorites, in whose land ye dwell: but as for me and my house, we will serve the LORD." },
  { reference: "Ruth 1:16", text: "And Ruth said, Intreat me not to leave thee, or to return from following after thee: for whither thou goest, I will go; and where thou lodgest, I will lodge: thy people shall be my people, and thy God my God:" },
  { reference: "1 Samuel 16:7", text: "But the LORD said unto Samuel, Look not on his countenance, or on the height of his stature; because I have refused him: for the LORD seeth not as man seeth; for man looketh on the outward appearance, but the LORD looketh on the heart." },
  { reference: "1 Samuel 17:47", text: "And all this assembly shall know that the LORD saveth not with sword and spear: for the battle is the LORD'S, and he will give you into our hands." },
  { reference: "2 Samuel 22:31", text: "As for God, his way is perfect; the word of the LORD is tried: he is a buckler to all them that trust in him." },
  { reference: "1 Kings 8:57", text: "The LORD our God be with us, as he was with our fathers: let him not leave us, nor forsake us:" },
  { reference: "1 Chronicles 16:11", text: "Seek the LORD and his strength, seek his face continually." },
  { reference: "1 Chronicles 16:34", text: "O give thanks unto the LORD; for he is good; for his mercy endureth for ever." },
  { reference: "1 Chronicles 28:20", text: "And David said to Solomon his son, Be strong and of good courage, and do it: fear not, nor be dismayed: for the LORD God, even my God, will be with thee; he will not fail thee, nor forsake thee, until thou hast finished all the work for the service of the house of the LORD." },
  { reference: "2 Chronicles 7:14", text: "If my people, which are called by my name, shall humble themselves, and pray, and seek my face, and turn from their wicked ways; then will I hear from heaven, and will forgive their sin, and will heal their land." },
  { reference: "2 Chronicles 16:9", text: "For the eyes of the LORD run to and fro throughout the whole earth, to shew himself strong in the behalf of them whose heart is perfect toward him. Herein thou hast done foolishly: therefore from henceforth thou shalt have wars." },
  { reference: "Ezra 8:22", text: "For I was ashamed to require of the king a band of soldiers and horsemen to help us against the enemy in the way: because we had spoken unto the king, saying, The hand of our God is upon all them for good that seek him; but his power and his wrath is against all them that forsake him." },
  { reference: "Nehemiah 8:10", text: "Then he said unto them, Go your way, eat the fat, and drink the sweet, and send portions unto them for whom nothing is prepared: for this day is holy unto our Lord: neither be ye sorry; for the joy of the LORD is your strength." },
  { reference: "Job 19:25", text: "For I know that my redeemer liveth, and that he shall stand at the latter day upon the earth:" },
  { reference: "Job 23:10", text: "But he knoweth the way that I take: when he hath tried me, I shall come forth as gold." },
  { reference: "Job 42:2", text: "I know that thou canst do every thing, and that no thought can be withholden from thee." },
  { reference: "Psalms 9:9", text: "The LORD also will be a refuge for the oppressed, a refuge in times of trouble." },
  { reference: "Psalms 16:11", text: "Thou wilt shew me the path of life: in thy presence is fulness of joy; at thy right hand there are pleasures for evermore." },
  { reference: "Psalms 18:2", text: "The LORD is my rock, and my fortress, and my deliverer; my God, my strength, in whom I will trust; my buckler, and the horn of my salvation, and my high tower." },
  { reference: "Psalms 19:1", text: "The heavens declare the glory of God; and the firmament sheweth his handywork." },
  { reference: "Psalms 20:7", text: "Some trust in chariots, and some in horses: but we will remember the name of the LORD our God." },
  { reference: "Psalms 27:1", text: "The LORD is my light and my salvation; whom shall I fear? the LORD is the strength of my life; of whom shall I be afraid?" },
  { reference: "Psalms 28:7", text: "The LORD is my strength and my shield; my heart trusted in him, and I am helped: therefore my heart greatly rejoiceth; and with my song will I praise him." },
  { reference: "Psalms 30:5", text: "For his anger endureth but a moment; in his favour is life: weeping may endure for a night, but joy cometh in the morning." },
  { reference: "Psalms 32:8", text: "I will instruct thee and teach thee in the way which thou shalt go: I will guide thee with mine eye." },
  { reference: "Psalms 34:4", text: "I sought the LORD, and he heard me, and delivered me from all my fears." },
  { reference: "Psalms 34:8", text: "O taste and see that the LORD is good: blessed is the man that trusteth in him." },
  { reference: "Psalms 34:18", text: "The LORD is nigh unto them that are of a broken heart; and saveth such as be of a contrite spirit." },
  { reference: "Psalms 37:4", text: "Delight thyself also in the LORD; and he shall give thee the desires of thine heart." },
  { reference: "Psalms 37:5", text: "Commit thy way unto the LORD; trust also in him; and he shall bring it to pass." },
  { reference: "Psalms 40:1", text: "I waited patiently for the LORD; and he inclined unto me, and heard my cry." },
  { reference: "Psalms 42:1", text: "As the hart panteth after the water brooks, so panteth my soul after thee, O God." },
  { reference: "Psalms 46:1", text: "God is our refuge and strength, a very present help in trouble." },
  { reference: "Psalms 46:10", text: "Be still, and know that I am God: I will be exalted among the heathen, I will be exalted in the earth." },
  { reference: "Psalms 51:10", text: "Create in me a clean heart, O God; and renew a right spirit within me." },
  { reference: "Psalms 55:22", text: "Cast thy burden upon the LORD, and he shall sustain thee: he shall never suffer the righteous to be moved." },
  { reference: "Psalms 56:3", text: "What time I am afraid, I will trust in thee." },
  { reference: "Psalms 62:1", text: "Truly my soul waiteth upon God: from him cometh my salvation." },
  { reference: "Psalms 68:19", text: "Blessed be the Lord, who daily loadeth us with benefits, even the God of our salvation. Selah." },
  { reference: "Psalms 71:3", text: "Be thou my strong habitation, whereunto I may continually resort: thou hast given commandment to save me; for thou art my rock and my fortress." },
  { reference: "Psalms 73:26", text: "My flesh and my heart faileth: but God is the strength of my heart, and my portion for ever." },
  { reference: "Psalms 84:11", text: "For the LORD God is a sun and shield: the LORD will give grace and glory: no good thing will he withhold from them that walk uprightly." },
  { reference: "Psalms 90:12", text: "So teach us to number our days, that we may apply our hearts unto wisdom." },
  { reference: "Psalms 91:1", text: "He that dwelleth in the secret place of the most High shall abide under the shadow of the Almighty." },
  { reference: "Psalms 91:4", text: "He shall cover thee with his feathers, and under his wings shalt thou trust: his truth shall be thy shield and buckler." },
  { reference: "Psalms 94:19", text: "In the multitude of my thoughts within me thy comforts delight my soul." },
  { reference: "Psalms 103:1", text: "Bless the LORD, O my soul: and all that is within me, bless his holy name." },
  { reference: "Psalms 103:12", text: "As far as the east is from the west, so far hath he removed our transgressions from us." },
  { reference: "Psalms 107:1", text: "O give thanks unto the LORD, for he is good: for his mercy endureth for ever." },
  { reference: "Psalms 118:24", text: "This is the day which the LORD hath made; we will rejoice and be glad in it." },
  { reference: "Psalms 119:105", text: "Thy word is a lamp unto my feet, and a light unto my path." },
  { reference: "Psalms 121:1", text: "I will lift up mine eyes unto the hills, from whence cometh my help." },
  { reference: "Psalms 121:2", text: "My help cometh from the LORD, which made heaven and earth." },
  { reference: "Psalms 126:5", text: "They that sow in tears shall reap in joy." },
  { reference: "Psalms 127:1", text: "Except the LORD build the house, they labour in vain that build it: except the LORD keep the city, the watchman waketh but in vain." },
  { reference: "Psalms 130:5", text: "I wait for the LORD, my soul doth wait, and in his word do I hope." },
  { reference: "Psalms 133:1", text: "Behold, how good and how pleasant it is for brethren to dwell together in unity!" },
  { reference: "Psalms 136:1", text: "O give thanks unto the LORD; for he is good: for his mercy endureth for ever." },
  { reference: "Psalms 139:14", text: "I will praise thee; for I am fearfully and wonderfully made: marvellous are thy works; and that my soul knoweth right well." },
  { reference: "Psalms 143:8", text: "Cause me to hear thy lovingkindness in the morning; for in thee do I trust: cause me to know the way wherein I should walk; for I lift up my soul unto thee." },
  { reference: "Psalms 145:18", text: "The LORD is nigh unto all them that call upon him, to all that call upon him in truth." },
  { reference: "Psalms 147:3", text: "He healeth the broken in heart, and bindeth up their wounds." },
  { reference: "Proverbs 3:5", text: "Trust in the LORD with all thine heart; and lean not unto thine own understanding." },
  { reference: "Proverbs 3:6", text: "In all thy ways acknowledge him, and he shall direct thy paths." },
  { reference: "Proverbs 4:23", text: "Keep thy heart with all diligence; for out of it are the issues of life." },
  { reference: "Proverbs 10:12", text: "Hatred stirreth up strifes: but love covereth all sins." },
  { reference: "Proverbs 11:25", text: "The liberal soul shall be made fat: and he that watereth shall be watered also himself." },
  { reference: "Proverbs 15:1", text: "A soft answer turneth away wrath: but grievous words stir up anger." },
  { reference: "Proverbs 16:3", text: "Commit thy works unto the LORD, and thy thoughts shall be established." },
  { reference: "Proverbs 16:9", text: "A man's heart deviseth his way: but the LORD directeth his steps." },
  { reference: "Proverbs 17:17", text: "A friend loveth at all times, and a brother is born for adversity." },
  { reference: "Proverbs 17:22", text: "A merry heart doeth good like a medicine: but a broken spirit drieth the bones." },
  { reference: "Proverbs 18:10", text: "The name of the LORD is a strong tower: the righteous runneth into it, and is safe." },
  { reference: "Proverbs 18:24", text: "A man that hath friends must shew himself friendly: and there is a friend that sticketh closer than a brother." },
  { reference: "Proverbs 19:21", text: "There are many devices in a man's heart; nevertheless the counsel of the LORD, that shall stand." },
  { reference: "Proverbs 22:1", text: "A good name is rather to be chosen than great riches, and loving favour rather than silver and gold." },
  { reference: "Proverbs 22:6", text: "Train up a child in the way he should go: and when he is old, he will not depart from it." },
  { reference: "Proverbs 27:17", text: "Iron sharpeneth iron; so a man sharpeneth the countenance of his friend." },
  { reference: "Proverbs 31:25", text: "Strength and honour are her clothing; and she shall rejoice in time to come." },
  { reference: "Ecclesiastes 3:1", text: "To every thing there is a season, and a time to every purpose under the heaven:" },
  { reference: "Ecclesiastes 4:9", text: "Two are better than one; because they have a good reward for their labour." },
  { reference: "Ecclesiastes 4:12", text: "And if one prevail against him, two shall withstand him; and a threefold cord is not quickly broken." },
  { reference: "Ecclesiastes 9:10", text: "Whatsoever thy hand findeth to do, do it with thy might; for there is no work, nor device, nor knowledge, nor wisdom, in the grave, whither thou goest." },
  { reference: "Isaiah 1:18", text: "Come now, and let us reason together, saith the LORD: though your sins be as scarlet, they shall be as white as snow; though they be red like crimson, they shall be as wool." },
  { reference: "Isaiah 9:6", text: "For unto us a child is born, unto us a son is given: and the government shall be upon his shoulder: and his name shall be called Wonderful, Counsellor, The mighty God, The everlasting Father, The Prince of Peace." },
  { reference: "Isaiah 12:2", text: "Behold, God is my salvation; I will trust, and not be afraid: for the LORD JEHOVAH is my strength and my song; he also is become my salvation." },
  { reference: "Isaiah 26:3", text: "Thou wilt keep him in perfect peace, whose mind is stayed on thee: because he trusteth in thee." },
  { reference: "Isaiah 30:21", text: "And thine ears shall hear a word behind thee, saying, This is the way, walk ye in it, when ye turn to the right hand, and when ye turn to the left." },
  { reference: "Isaiah 40:8", text: "The grass withereth, the flower fadeth: but the word of our God shall stand for ever." },
  { reference: "Isaiah 40:28", text: "Hast thou not known? hast thou not heard, that the everlasting God, the LORD, the Creator of the ends of the earth, fainteth not, neither is weary? there is no searching of his understanding." },
  { reference: "Isaiah 40:29", text: "He giveth power to the faint; and to them that have no might he increaseth strength." },
  { reference: "Isaiah 40:31", text: "But they that wait upon the LORD shall renew their strength; they shall mount up with wings as eagles; they shall run, and not be weary; and they shall walk, and not faint." },
  { reference: "Isaiah 41:10", text: "Fear thou not; for I am with thee: be not dismayed; for I am thy God: I will strengthen thee; yea, I will help thee; yea, I will uphold thee with the right hand of my righteousness." },
  { reference: "Isaiah 41:13", text: "For I the LORD thy God will hold thy right hand, saying unto thee, Fear not; I will help thee." },
  { reference: "Isaiah 43:2", text: "When thou passest through the waters, I will be with thee; and through the rivers, they shall not overflow thee: when thou walkest through the fire, thou shalt not be burned; neither shall the flame kindle upon thee." },
  { reference: "Isaiah 43:18", text: "Remember ye not the former things, neither consider the things of old." },
  { reference: "Isaiah 43:19", text: "Behold, I will do a new thing; now it shall spring forth; shall ye not know it? I will even make a way in the wilderness, and rivers in the desert." },
  { reference: "Isaiah 46:4", text: "And even to your old age I am he; and even to hoar hairs will I carry you: I have made, and I will bear; even I will carry, and will deliver you." },
  { reference: "Isaiah 53:5", text: "But he was wounded for our transgressions, he was bruised for our iniquities: the chastisement of our peace was upon him; and with his stripes we are healed." },
  { reference: "Isaiah 55:8", text: "For my thoughts are not your thoughts, neither are your ways my ways, saith the LORD." },
  { reference: "Isaiah 55:11", text: "So shall my word be that goeth forth out of my mouth: it shall not return unto me void, but it shall accomplish that which I please, and it shall prosper in the thing whereto I sent it." },
  { reference: "Isaiah 58:11", text: "And the LORD shall guide thee continually, and satisfy thy soul in drought, and make fat thy bones: and thou shalt be like a watered garden, and like a spring of water, whose waters fail not." },
  { reference: "Isaiah 60:1", text: "Arise, shine; for thy light is come, and the glory of the LORD is risen upon thee." },
  { reference: "Isaiah 64:8", text: "But now, O LORD, thou art our father; we are the clay, and thou our potter; and we all are the work of thy hand." },
  { reference: "Jeremiah 17:7", text: "Blessed is the man that trusteth in the LORD, and whose hope the LORD is." },
  { reference: "Jeremiah 29:11", text: "For I know the thoughts that I think toward you, saith the LORD, thoughts of peace, and not of evil, to give you an expected end." },
  { reference: "Jeremiah 31:3", text: "The LORD hath appeared of old unto me, saying, Yea, I have loved thee with an everlasting love: therefore with lovingkindness have I drawn thee." },
  { reference: "Jeremiah 32:17", text: "Ah Lord GOD! behold, thou hast made the heaven and the earth by thy great power and stretched out arm, and there is nothing too hard for thee:" },
  { reference: "Jeremiah 33:3", text: "Call unto me, and I will answer thee, and shew thee great and mighty things, which thou knowest not." },
  { reference: "Lamentations 3:22", text: "It is of the LORD'S mercies that we are not consumed, because his compassions fail not." },
  { reference: "Lamentations 3:23", text: "They are new every morning: great is thy faithfulness." },
  { reference: "Ezekiel 36:26", text: "A new heart also will I give you, and a new spirit will I put within you: and I will take away the stony heart out of your flesh, and I will give you an heart of flesh." },
  { reference: "Daniel 2:22", text: "He revealeth the deep and secret things: he knoweth what is in the darkness, and the light dwelleth with him." },
  { reference: "Daniel 3:17", text: "If it be so, our God whom we serve is able to deliver us from the burning fiery furnace, and he will deliver us out of thine hand, O king." },
  { reference: "Hosea 6:3", text: "Then shall we know, if we follow on to know the LORD: his going forth is prepared as the morning; and he shall come unto us as the rain, as the latter and former rain unto the earth." },
  { reference: "Joel 2:25", text: "And I will restore to you the years that the locust hath eaten, the cankerworm, and the caterpiller, and the palmerworm, my great army which I sent among you." },
  { reference: "Micah 6:8", text: "He hath shewed thee, O man, what is good; and what doth the LORD require of thee, but to do justly, and to love mercy, and to walk humbly with thy God?" },
  { reference: "Micah 7:7", text: "Therefore I will look unto the LORD; I will wait for the God of my salvation: my God will hear me." },
  { reference: "Nahum 1:7", text: "The LORD is good, a strong hold in the day of trouble; and he knoweth them that trust in him." },
  { reference: "Habakkuk 3:19", text: "The LORD God is my strength, and he will make my feet like hinds' feet, and he will make me to walk upon mine high places. To the chief singer on my stringed instruments." },
  { reference: "Zephaniah 3:17", text: "The LORD thy God in the midst of thee is mighty; he will save, he will rejoice over thee with joy; he will rest in his love, he will joy over thee with singing." },
  { reference: "Haggai 2:9", text: "The glory of this latter house shall be greater than of the former, saith the LORD of hosts: and in this place will I give peace, saith the LORD of hosts." },
  { reference: "Zechariah 4:6", text: "Then he answered and spake unto me, saying, This is the word of the LORD unto Zerubbabel, saying, Not by might, nor by power, but by my spirit, saith the LORD of hosts." },
  { reference: "Malachi 3:10", text: "Bring ye all the tithes into the storehouse, that there may be meat in mine house, and prove me now herewith, saith the LORD of hosts, if I will not open you the windows of heaven, and pour you out a blessing, that there shall not be room enough to receive it." },
  { reference: "Matthew 5:9", text: "Blessed are the peacemakers: for they shall be called the children of God." },
  { reference: "Matthew 5:14", text: "Ye are the light of the world. A city that is set on an hill cannot be hid." },
  { reference: "Matthew 5:16", text: "Let your light so shine before men, that they may see your good works, and glorify your Father which is in heaven." },
  { reference: "Matthew 6:33", text: "But seek ye first the kingdom of God, and his righteousness; and all these things shall be added unto you." },
  { reference: "Matthew 6:34", text: "Take therefore no thought for the morrow: for the morrow shall take thought for the things of itself. Sufficient unto the day is the evil thereof." },
  { reference: "Matthew 7:7", text: "Ask, and it shall be given you; seek, and ye shall find; knock, and it shall be opened unto you:" },
  { reference: "Matthew 7:12", text: "Therefore all things whatsoever ye would that men should do to you, do ye even so to them: for this is the law and the prophets." },
  { reference: "Matthew 11:28", text: "Come unto me, all ye that labour and are heavy laden, and I will give you rest." },
  { reference: "Matthew 11:29", text: "Take my yoke upon you, and learn of me; for I am meek and lowly in heart: and ye shall find rest unto your souls." },
  { reference: "Matthew 17:20", text: "And Jesus said unto them, Because of your unbelief: for verily I say unto you, If ye have faith as a grain of mustard seed, ye shall say unto this mountain, Remove hence to yonder place; and it shall remove; and nothing shall be impossible unto you." },
  { reference: "Matthew 19:26", text: "But Jesus beheld them, and said unto them, With men this is impossible; but with God all things are possible." },
  { reference: "Matthew 28:19", text: "Go ye therefore, and teach all nations, baptizing them in the name of the Father, and of the Son, and of the Holy Ghost:" },
  { reference: "Matthew 28:20", text: "Teaching them to observe all things whatsoever I have commanded you: and, lo, I am with you alway, even unto the end of the world. Amen." },
  { reference: "Mark 9:23", text: "Jesus said unto him, If thou canst believe, all things are possible to him that believeth." },
  { reference: "Mark 10:27", text: "And Jesus looking upon them saith, With men it is impossible, but not with God: for with God all things are possible." },
  { reference: "Mark 11:24", text: "Therefore I say unto you, What things soever ye desire, when ye pray, believe that ye receive them, and ye shall have them." },
  { reference: "Mark 12:30", text: "And thou shalt love the Lord thy God with all thy heart, and with all thy soul, and with all thy mind, and with all thy strength: this is the first commandment." },
  { reference: "Mark 12:31", text: "And the second is like, namely this, Thou shalt love thy neighbour as thyself. There is none other commandment greater than these." },
  { reference: "Luke 1:1", text: "Forasmuch as many have taken in hand to set forth in order a declaration of those things which are most surely believed among us," },
  { reference: "Luke 1:37", text: "For with God nothing shall be impossible." },
  { reference: "Luke 2:10", text: "And the angel said unto them, Fear not: for, behold, I bring you good tidings of great joy, which shall be to all people." },
  { reference: "Luke 6:31", text: "And as ye would that men should do to you, do ye also to them likewise." },
  { reference: "Luke 6:38", text: "Give, and it shall be given unto you; good measure, pressed down, and shaken together, and running over, shall men give into your bosom. For with the same measure that ye mete withal it shall be measured to you again." },
  { reference: "Luke 12:7", text: "But even the very hairs of your head are all numbered. Fear not therefore: ye are of more value than many sparrows." },
  { reference: "Luke 15:7", text: "I say unto you, that likewise joy shall be in heaven over one sinner that repenteth, more than over ninety and nine just persons, which need no repentance." },
  { reference: "John 1:1", text: "In the beginning was the Word, and the Word was with God, and the Word was God." },
  { reference: "John 1:12", text: "But as many as received him, to them gave he power to become the sons of God, even to them that believe on his name:" },
  { reference: "John 3:16", text: "For God so loved the world, that he gave his only begotten Son, that whosoever believeth in him should not perish, but have everlasting life." },
  { reference: "John 8:12", text: "Then spake Jesus again unto them, saying, I am the light of the world: he that followeth me shall not walk in darkness, but shall have the light of life." },
  { reference: "John 10:10", text: "The thief cometh not, but for to steal, and to kill, and to destroy: I am come that they might have life, and that they might have it more abundantly." },
  { reference: "John 11:25", text: "Jesus said unto her, I am the resurrection, and the life: he that believeth in me, though he were dead, yet shall he live:" },
  { reference: "John 13:34", text: "A new commandment I give unto you, That ye love one another; as I have loved you, that ye also love one another." },
  { reference: "John 14:6", text: "Jesus saith unto him, I am the way, the truth, and the life: no man cometh unto the Father, but by me." },
  { reference: "John 14:27", text: "Peace I leave with you, my peace I give unto you: not as the world giveth, give I unto you. Let not your heart be troubled, neither let it be afraid." },
  { reference: "John 15:5", text: "I am the vine, ye are the branches: He that abideth in me, and I in him, the same bringeth forth much fruit: for without me ye can do nothing." },
  { reference: "John 15:13", text: "Greater love hath no man than this, that a man lay down his life for his friends." },
  { reference: "John 16:33", text: "These things I have spoken unto you, that in me ye might have peace. In the world ye shall have tribulation: but be of good cheer; I have overcome the world." },
  { reference: "Acts 1:8", text: "But ye shall receive power, after that the Holy Ghost is come upon you: and ye shall be witnesses unto me both in Jerusalem, and in all Judaea, and in Samaria, and unto the uttermost part of the earth." },
  { reference: "Acts 2:21", text: "And it shall come to pass, that whosoever shall call on the name of the Lord shall be saved." },
  { reference: "Acts 4:12", text: "Neither is there salvation in any other: for there is none other name under heaven given among men, whereby we must be saved." },
  { reference: "Acts 16:31", text: "And they said, Believe on the Lord Jesus Christ, and thou shalt be saved, and thy house." },
  { reference: "Acts 20:35", text: "I have shewed you all things, how that so labouring ye ought to support the weak, and to remember the words of the Lord Jesus, how he said, It is more blessed to give than to receive." },
  { reference: "Romans 5:8", text: "But God commendeth his love toward us, in that, while we were yet sinners, Christ died for us." },
  { reference: "Romans 8:1", text: "There is therefore now no condemnation to them which are in Christ Jesus, who walk not after the flesh, but after the Spirit." },
  { reference: "Romans 8:28", text: "And we know that all things work together for good to them that love God, to them who are the called according to his purpose." },
  { reference: "Romans 8:31", text: "What shall we then say to these things? If God be for us, who can be against us?" },
  { reference: "Romans 8:38", text: "For I am persuaded, that neither death, nor life, nor angels, nor principalities, nor powers, nor things present, nor things to come," },
  { reference: "Romans 8:39", text: "Nor height, nor depth, nor any other creature, shall be able to separate us from the love of God, which is in Christ Jesus our Lord." },
  { reference: "Romans 10:9", text: "That if thou shalt confess with thy mouth the Lord Jesus, and shalt believe in thine heart that God hath raised him from the dead, thou shalt be saved." },
  { reference: "Romans 12:2", text: "And be not conformed to this world: but be ye transformed by the renewing of your mind, that ye may prove what is that good, and acceptable, and perfect, will of God." },
  { reference: "Romans 12:12", text: "Rejoicing in hope; patient in tribulation; continuing instant in prayer;" },
  { reference: "Romans 15:13", text: "Now the God of hope fill you with all joy and peace in believing, that ye may abound in hope, through the power of the Holy Ghost." },
  { reference: "1 Corinthians 2:9", text: "But as it is written, Eye hath not seen, nor ear heard, neither have entered into the heart of man, the things which God hath prepared for them that love him." },
  { reference: "1 Corinthians 10:13", text: "There hath no temptation taken you but such as is common to man: but God is faithful, who will not suffer you to be tempted above that ye are able; but will with the temptation also make a way to escape, that ye may be able to bear it." },
  { reference: "1 Corinthians 13:4", text: "Charity suffereth long, and is kind; charity envieth not; charity vaunteth not itself, is not puffed up," },
  { reference: "1 Corinthians 13:7", text: "Beareth all things, believeth all things, hopeth all things, endureth all things." },
  { reference: "1 Corinthians 13:13", text: "And now abideth faith, hope, charity, these three; but the greatest of these is charity." },
  { reference: "1 Corinthians 15:58", text: "Therefore, my beloved brethren, be ye stedfast, unmoveable, always abounding in the work of the Lord, forasmuch as ye know that your labour is not in vain in the Lord." },
  { reference: "1 Corinthians 16:14", text: "Let all your things be done with charity." },
  { reference: "2 Corinthians 1:3", text: "Blessed be God, even the Father of our Lord Jesus Christ, the Father of mercies, and the God of all comfort;" },
  { reference: "2 Corinthians 1:4", text: "Who comforteth us in all our tribulation, that we may be able to comfort them which are in any trouble, by the comfort wherewith we ourselves are comforted of God." },
  { reference: "2 Corinthians 4:16", text: "For which cause we faint not; but though our outward man perish, yet the inward man is renewed day by day." },
  { reference: "2 Corinthians 4:18", text: "While we look not at the things which are seen, but at the things which are not seen: for the things which are seen are temporal; but the things which are not seen are eternal." },
  { reference: "2 Corinthians 5:7", text: "(For we walk by faith, not by sight:)" },
  { reference: "2 Corinthians 5:17", text: "Therefore if any man be in Christ, he is a new creature: old things are passed away; behold, all things are become new." },
  { reference: "2 Corinthians 9:7", text: "Every man according as he purposeth in his heart, so let him give; not grudgingly, or of necessity: for God loveth a cheerful giver." },
  { reference: "2 Corinthians 12:9", text: "And he said unto me, My grace is sufficient for thee: for my strength is made perfect in weakness. Most gladly therefore will I rather glory in my infirmities, that the power of Christ may rest upon me." },
  { reference: "Galatians 2:20", text: "I am crucified with Christ: nevertheless I live; yet not I, but Christ liveth in me: and the life which I now live in the flesh I live by the faith of the Son of God, who loved me, and gave himself for me." },
  { reference: "Galatians 5:13", text: "For, brethren, ye have been called unto liberty; only use not liberty for an occasion to the flesh, but by love serve one another." },
  { reference: "Galatians 5:22", text: "But the fruit of the Spirit is love, joy, peace, longsuffering, gentleness, goodness, faith," },
  { reference: "Galatians 6:9", text: "And let us not be weary in well doing: for in due season we shall reap, if we faint not." },
  { reference: "Ephesians 2:8", text: "For by grace are ye saved through faith; and that not of yourselves: it is the gift of God:" },
  { reference: "Ephesians 2:10", text: "For we are his workmanship, created in Christ Jesus unto good works, which God hath before ordained that we should walk in them." },
  { reference: "Ephesians 3:20", text: "Now unto him that is able to do exceeding abundantly above all that we ask or think, according to the power that worketh in us," },
  { reference: "Ephesians 4:2", text: "With all lowliness and meekness, with longsuffering, forbearing one another in love;" },
  { reference: "Ephesians 4:32", text: "And be ye kind one to another, tenderhearted, forgiving one another, even as God for Christ's sake hath forgiven you." },
  { reference: "Ephesians 6:10", text: "Finally, my brethren, be strong in the Lord, and in the power of his might." },
  { reference: "Philippians 1:6", text: "Being confident of this very thing, that he which hath begun a good work in you will perform it until the day of Jesus Christ:" },
  { reference: "Philippians 2:3", text: "Let nothing be done through strife or vainglory; but in lowliness of mind let each esteem other better than themselves." },
  { reference: "Philippians 4:6", text: "Be careful for nothing; but in every thing by prayer and supplication with thanksgiving let your requests be made known unto God." },
  { reference: "Philippians 4:7", text: "And the peace of God, which passeth all understanding, shall keep your hearts and minds through Christ Jesus." },
  { reference: "Philippians 4:8", text: "Finally, brethren, whatsoever things are true, whatsoever things are honest, whatsoever things are just, whatsoever things are pure, whatsoever things are lovely, whatsoever things are of good report; if there be any virtue, and if there be any praise, think on these things." },
  { reference: "Philippians 4:13", text: "I can do all things through Christ which strengtheneth me." },
  { reference: "Philippians 4:19", text: "But my God shall supply all your need according to his riches in glory by Christ Jesus." },
  { reference: "Colossians 3:2", text: "Set your affection on things above, not on things on the earth." },
  { reference: "Colossians 3:12", text: "Put on therefore, as the elect of God, holy and beloved, bowels of mercies, kindness, humbleness of mind, meekness, longsuffering;" },
  { reference: "Colossians 3:23", text: "And whatsoever ye do, do it heartily, as to the Lord, and not unto men;" },
  { reference: "1 Thessalonians 5:11", text: "Wherefore comfort yourselves together, and edify one another, even as also ye do." },
  { reference: "1 Thessalonians 5:16", text: "Rejoice evermore." },
  { reference: "1 Thessalonians 5:17", text: "Pray without ceasing." },
  { reference: "1 Thessalonians 5:18", text: "In every thing give thanks: for this is the will of God in Christ Jesus concerning you." },
  { reference: "2 Thessalonians 3:3", text: "But the Lord is faithful, who shall stablish you, and keep you from evil." },
  { reference: "1 Timothy 4:12", text: "Let no man despise thy youth; but be thou an example of the believers, in word, in conversation, in charity, in spirit, in faith, in purity." },
  { reference: "1 Timothy 6:6", text: "But godliness with contentment is great gain." },
  { reference: "2 Timothy 1:7", text: "For God hath not given us the spirit of fear; but of power, and of love, and of a sound mind." },
  { reference: "2 Timothy 2:15", text: "Study to shew thyself approved unto God, a workman that needeth not to be ashamed, rightly dividing the word of truth." },
  { reference: "Titus 2:7", text: "In all things shewing thyself a pattern of good works: in doctrine shewing uncorruptness, gravity, sincerity," },
  { reference: "Philemon 1:6", text: "That the communication of thy faith may become effectual by the acknowledging of every good thing which is in you in Christ Jesus." },
  { reference: "Hebrews 4:12", text: "For the word of God is quick, and powerful, and sharper than any twoedged sword, piercing even to the dividing asunder of soul and spirit, and of the joints and marrow, and is a discerner of the thoughts and intents of the heart." },
  { reference: "Hebrews 4:16", text: "Let us therefore come boldly unto the throne of grace, that we may obtain mercy, and find grace to help in time of need." },
  { reference: "Hebrews 10:24", text: "And let us consider one another to provoke unto love and to good works:" },
  { reference: "Hebrews 11:1", text: "Now faith is the substance of things hoped for, the evidence of things not seen." },
  { reference: "Hebrews 11:6", text: "But without faith it is impossible to please him: for he that cometh to God must believe that he is, and that he is a rewarder of them that diligently seek him." },
  { reference: "Hebrews 12:1", text: "Wherefore seeing we also are compassed about with so great a cloud of witnesses, let us lay aside every weight, and the sin which doth so easily beset us, and let us run with patience the race that is set before us," },
  { reference: "Hebrews 13:5", text: "Let your conversation be without covetousness; and be content with such things as ye have: for he hath said, I will never leave thee, nor forsake thee." },
  { reference: "Hebrews 13:8", text: "Jesus Christ the same yesterday, and to day, and for ever." },
  { reference: "James 1:2", text: "My brethren, count it all joy when ye fall into divers temptations;" },
  { reference: "James 1:5", text: "If any of you lack wisdom, let him ask of God, that giveth to all men liberally, and upbraideth not; and it shall be given him." },
  { reference: "James 1:12", text: "Blessed is the man that endureth temptation: for when he is tried, he shall receive the crown of life, which the Lord hath promised to them that love him." },
  { reference: "James 1:17", text: "Every good gift and every perfect gift is from above, and cometh down from the Father of lights, with whom is no variableness, neither shadow of turning." },
  { reference: "James 1:19", text: "Wherefore, my beloved brethren, let every man be swift to hear, slow to speak, slow to wrath:" },
  { reference: "James 4:7", text: "Submit yourselves therefore to God. Resist the devil, and he will flee from you." },
  { reference: "James 4:8", text: "Draw nigh to God, and he will draw nigh to you. Cleanse your hands, ye sinners; and purify your hearts, ye double minded." },
  { reference: "1 Peter 1:3", text: "Blessed be the God and Father of our Lord Jesus Christ, which according to his abundant mercy hath begotten us again unto a lively hope by the resurrection of Jesus Christ from the dead," },
  { reference: "1 Peter 3:15", text: "But sanctify the Lord God in your hearts: and be ready always to give an answer to every man that asketh you a reason of the hope that is in you with meekness and fear:" },
  { reference: "1 Peter 4:8", text: "And above all things have fervent charity among yourselves: for charity shall cover the multitude of sins." },
  { reference: "1 Peter 5:7", text: "Casting all your care upon him; for he careth for you." },
  { reference: "2 Peter 1:3", text: "According as his divine power hath given unto us all things that pertain unto life and godliness, through the knowledge of him that hath called us to glory and virtue:" },
  { reference: "2 Peter 3:9", text: "The Lord is not slack concerning his promise, as some men count slackness; but is longsuffering to us-ward, not willing that any should perish, but that all should come to repentance." },
  { reference: "1 John 1:9", text: "If we confess our sins, he is faithful and just to forgive us our sins, and to cleanse us from all unrighteousness." },
  { reference: "1 John 3:1", text: "Behold, what manner of love the Father hath bestowed upon us, that we should be called the sons of God: therefore the world knoweth us not, because it knew him not." },
  { reference: "1 John 3:18", text: "My little children, let us not love in word, neither in tongue; but in deed and in truth." },
  { reference: "1 John 4:7", text: "Beloved, let us love one another: for love is of God; and every one that loveth is born of God, and knoweth God." },
  { reference: "1 John 4:18", text: "There is no fear in love; but perfect love casteth out fear: because fear hath torment. He that feareth is not made perfect in love." },
  { reference: "1 John 4:19", text: "We love him, because he first loved us." },
  { reference: "1 John 5:4", text: "For whatsoever is born of God overcometh the world: and this is the victory that overcometh the world, even our faith." },
  { reference: "Jude 1:24", text: "Now unto him that is able to keep you from falling, and to present you faultless before the presence of his glory with exceeding joy," },
  { reference: "Revelation 1:8", text: "I am Alpha and Omega, the beginning and the ending, saith the Lord, which is, and which was, and which is to come, the Almighty." },
  { reference: "Revelation 3:20", text: "Behold, I stand at the door, and knock: if any man hear my voice, and open the door, I will come in to him, and will sup with him, and he with me." },
  { reference: "Revelation 21:4", text: "And God shall wipe away all tears from their eyes; and there shall be no more death, neither sorrow, nor crying, neither shall there be any more pain: for the former things are passed away." },
  { reference: "Revelation 21:5", text: "And he that sat upon the throne said, Behold, I make all things new. And he said unto me, Write: for these words are true and faithful." },
  { reference: "Psalms 1:1", text: "Blessed is the man that walketh not in the counsel of the ungodly, nor standeth in the way of sinners, nor sitteth in the seat of the scornful." },
  { reference: "Psalms 2:1", text: "Why do the heathen rage, and the people imagine a vain thing?" },
  { reference: "Psalms 3:1", text: "LORD, how are they increased that trouble me! many are they that rise up against me." },
  { reference: "Psalms 4:1", text: "Hear me when I call, O God of my righteousness: thou hast enlarged me when I was in distress; have mercy upon me, and hear my prayer." },
  { reference: "Psalms 5:1", text: "Give ear to my words, O LORD, consider my meditation." },
  { reference: "Psalms 6:1", text: "O LORD, rebuke me not in thine anger, neither chasten me in thy hot displeasure." },
  { reference: "Psalms 7:1", text: "O LORD my God, in thee do I put my trust: save me from all them that persecute me, and deliver me:" },
  { reference: "Psalms 8:1", text: "O LORD our Lord, how excellent is thy name in all the earth! who hast set thy glory above the heavens." },
  { reference: "Psalms 9:1", text: "I will praise thee, O LORD, with my whole heart; I will shew forth all thy marvellous works." },
  { reference: "Psalms 10:1", text: "Why standest thou afar off, O LORD? why hidest thou thyself in times of trouble?" },
  { reference: "Psalms 11:1", text: "In the LORD put I my trust: how say ye to my soul, Flee as a bird to your mountain?" },
  { reference: "Psalms 12:1", text: "Help, LORD; for the godly man ceaseth; for the faithful fail from among the children of men." },
  { reference: "Psalms 13:1", text: "How long wilt thou forget me, O LORD? for ever? how long wilt thou hide thy face from me?" },
  { reference: "Psalms 14:1", text: "The fool hath said in his heart, There is no God. They are corrupt, they have done abominable works, there is none that doeth good." },
  { reference: "Psalms 15:1", text: "LORD, who shall abide in thy tabernacle? who shall dwell in thy holy hill?" },
  { reference: "Psalms 16:1", text: "Preserve me, O God: for in thee do I put my trust." },
  { reference: "Psalms 17:1", text: "Hear the right, O LORD, attend unto my cry, give ear unto my prayer, that goeth not out of feigned lips." },
  { reference: "Psalms 18:1", text: "I will love thee, O LORD, my strength." },
  { reference: "Psalms 20:1", text: "The LORD hear thee in the day of trouble; the name of the God of Jacob defend thee;" },
  { reference: "Psalms 21:1", text: "The king shall joy in thy strength, O LORD; and in thy salvation how greatly shall he rejoice!" },
  { reference: "Psalms 22:1", text: "My God, my God, why hast thou forsaken me? why art thou so far from helping me, and from the words of my roaring?" },
  { reference: "Psalms 23:1", text: "The LORD is my shepherd; I shall not want." },
  { reference: "Psalms 24:1", text: "The earth is the LORD'S, and the fulness thereof; the world, and they that dwell therein." },
  { reference: "Psalms 25:1", text: "Unto thee, O LORD, do I lift up my soul." },
  { reference: "Psalms 26:1", text: "Judge me, O LORD; for I have walked in mine integrity: I have trusted also in the LORD; therefore I shall not slide." },
  { reference: "Psalms 28:1", text: "Unto thee will I cry, O LORD my rock; be not silent to me: lest, if thou be silent to me, I become like them that go down into the pit." },
  { reference: "Psalms 29:1", text: "Give unto the LORD, O ye mighty, give unto the LORD glory and strength." },
  { reference: "Psalms 30:1", text: "I will extol thee, O LORD; for thou hast lifted me up, and hast not made my foes to rejoice over me." },
  { reference: "Psalms 31:1", text: "In thee, O LORD, do I put my trust; let me never be ashamed: deliver me in thy righteousness." },
  { reference: "Psalms 32:1", text: "Blessed is he whose transgression is forgiven, whose sin is covered." },
  { reference: "Psalms 33:1", text: "Rejoice in the LORD, O ye righteous: for praise is comely for the upright." },
  { reference: "Psalms 34:1", text: "I will bless the LORD at all times: his praise shall continually be in my mouth." },
  { reference: "Psalms 35:1", text: "Plead my cause, O LORD, with them that strive with me: fight against them that fight against me." },
  { reference: "Psalms 36:1", text: "The transgression of the wicked saith within my heart, that there is no fear of God before his eyes." },
  { reference: "Psalms 37:1", text: "Fret not thyself because of evildoers, neither be thou envious against the workers of iniquity." },
  { reference: "Psalms 38:1", text: "O LORD, rebuke me not in thy wrath: neither chasten me in thy hot displeasure." },
  { reference: "Psalms 39:1", text: "I said, I will take heed to my ways, that I sin not with my tongue: I will keep my mouth with a bridle, while the wicked is before me." },
  { reference: "Psalms 41:1", text: "Blessed is he that considereth the poor: the LORD will deliver him in time of trouble." },
  { reference: "Psalms 43:1", text: "Judge me, O God, and plead my cause against an ungodly nation: O deliver me from the deceitful and unjust man." },
  { reference: "Psalms 44:1", text: "We have heard with our ears, O God, our fathers have told us, what work thou didst in their days, in the times of old." },
  { reference: "Psalms 45:1", text: "My heart is inditing a good matter: I speak of the things which I have made touching the king: my tongue is the pen of a ready writer." },
  { reference: "Psalms 47:1", text: "O clap your hands, all ye people; shout unto God with the voice of triumph." },
  { reference: "Psalms 48:1", text: "Great is the LORD, and greatly to be praised in the city of our God, in the mountain of his holiness." },
  { reference: "Psalms 49:1", text: "Hear this, all ye people; give ear, all ye inhabitants of the world:" },
  { reference: "Psalms 50:1", text: "The mighty God, even the LORD, hath spoken, and called the earth from the rising of the sun unto the going down thereof." },
  { reference: "Psalms 51:1", text: "Have mercy upon me, O God, according to thy lovingkindness: according unto the multitude of thy tender mercies blot out my transgressions." },
  { reference: "Psalms 52:1", text: "Why boastest thou thyself in mischief, O mighty man? the goodness of God endureth continually." },
  { reference: "Psalms 53:1", text: "The fool hath said in his heart, There is no God. Corrupt are they, and have done abominable iniquity: there is none that doeth good." },
  { reference: "Psalms 54:1", text: "Save me, O God, by thy name, and judge me by thy strength." },
  { reference: "Psalms 55:1", text: "Give ear to my prayer, O God; and hide not thyself from my supplication." },
  { reference: "Psalms 56:1", text: "Be merciful unto me, O God: for man would swallow me up; he fighting daily oppresseth me." },
  { reference: "Psalms 57:1", text: "Be merciful unto me, O God, be merciful unto me: for my soul trusteth in thee: yea, in the shadow of thy wings will I make my refuge, until these calamities be overpast." },
  { reference: "Psalms 58:1", text: "Do ye indeed speak righteousness, O congregation? do ye judge uprightly, O ye sons of men?" },
  { reference: "Psalms 59:1", text: "Deliver me from mine enemies, O my God: defend me from them that rise up against me." },
  { reference: "Psalms 60:1", text: "O God, thou hast cast us off, thou hast scattered us, thou hast been displeased; O turn thyself to us again." },
  { reference: "Psalms 61:1", text: "Hear my cry, O God; attend unto my prayer." },
  { reference: "Psalms 63:1", text: "O God, thou art my God; early will I seek thee: my soul thirsteth for thee, my flesh longeth for thee in a dry and thirsty land, where no water is;" },
  { reference: "Psalms 64:1", text: "Hear my voice, O God, in my prayer: preserve my life from fear of the enemy." },
  { reference: "Psalms 65:1", text: "Praise waiteth for thee, O God, in Sion: and unto thee shall the vow be performed." },
  { reference: "Psalms 66:1", text: "Make a joyful noise unto God, all ye lands:" },
  { reference: "Psalms 67:1", text: "God be merciful unto us, and bless us; and cause his face to shine upon us; Selah." },
  { reference: "Psalms 68:1", text: "Let God arise, let his enemies be scattered: let them also that hate him flee before him." },
  { reference: "Psalms 69:1", text: "Save me, O God; for the waters are come in unto my soul." },
  { reference: "Psalms 70:1", text: "Make haste, O God, to deliver me; make haste to help me, O LORD." },
  { reference: "Psalms 71:1", text: "In thee, O LORD, do I put my trust: let me never be put to confusion." },
  { reference: "Psalms 72:1", text: "Give the king thy judgments, O God, and thy righteousness unto the king's son." },
  { reference: "Psalms 73:1", text: "Truly God is good to Israel, even to such as are of a clean heart." },
  { reference: "Psalms 74:1", text: "O God, why hast thou cast us off for ever? why doth thine anger smoke against the sheep of thy pasture?" },
  { reference: "Psalms 75:1", text: "Unto thee, O God, do we give thanks, unto thee do we give thanks: for that thy name is near thy wondrous works declare." },
  { reference: "Psalms 76:1", text: "In Judah is God known: his name is great in Israel." },
  { reference: "Psalms 77:1", text: "I cried unto God with my voice, even unto God with my voice; and he gave ear unto me." },
  { reference: "Psalms 78:1", text: "Give ear, O my people, to my law: incline your ears to the words of my mouth." },
  { reference: "Psalms 79:1", text: "O God, the heathen are come into thine inheritance; thy holy temple have they defiled; they have laid Jerusalem on heaps." },
  { reference: "Psalms 80:1", text: "Give ear, O Shepherd of Israel, thou that leadest Joseph like a flock; thou that dwellest between the cherubims, shine forth." },
  { reference: "Psalms 81:1", text: "Sing aloud unto God our strength: make a joyful noise unto the God of Jacob." },
  { reference: "Psalms 82:1", text: "God standeth in the congregation of the mighty; he judgeth among the gods." },
  { reference: "Psalms 83:1", text: "Keep not thou silence, O God: hold not thy peace, and be not still, O God." },
  { reference: "Psalms 84:1", text: "How amiable are thy tabernacles, O LORD of hosts!" },
  { reference: "Psalms 85:1", text: "LORD, thou hast been favourable unto thy land: thou hast brought back the captivity of Jacob." },
  { reference: "Psalms 86:1", text: "Bow down thine ear, O LORD, hear me: for I am poor and needy." },
  { reference: "Psalms 87:1", text: "His foundation is in the holy mountains." },
  { reference: "Psalms 88:1", text: "O LORD God of my salvation, I have cried day and night before thee:" },
  { reference: "Psalms 89:1", text: "I will sing of the mercies of the LORD for ever: with my mouth will I make known thy faithfulness to all generations." },
  { reference: "Psalms 90:1", text: "Lord, thou hast been our dwelling place in all generations." },
  { reference: "Psalms 92:1", text: "It is a good thing to give thanks unto the LORD, and to sing praises unto thy name, O most High:" },
  { reference: "Psalms 93:1", text: "The LORD reigneth, he is clothed with majesty; the LORD is clothed with strength, wherewith he hath girded himself: the world also is stablished, that it cannot be moved." },
  { reference: "Psalms 94:1", text: "O LORD God, to whom vengeance belongeth; O God, to whom vengeance belongeth, shew thyself." },
  { reference: "Psalms 95:1", text: "O come, let us sing unto the LORD: let us make a joyful noise to the rock of our salvation." },
  { reference: "Psalms 96:1", text: "O sing unto the LORD a new song: sing unto the LORD, all the earth." },
];

function dayOfYearUTC(date: Date): number {
  const startOfYearUTC = Date.UTC(date.getUTCFullYear(), 0, 1);
  const todayUTC = Date.UTC(date.getUTCFullYear(), date.getUTCMonth(), date.getUTCDate());
  return Math.floor((todayUTC - startOfYearUTC) / 86_400_000);
}

export function getTodaysVerse(now: Date = new Date()): DailyVerse {
  const index = dayOfYearUTC(now) % DAILY_VERSES.length;
  return DAILY_VERSES[index];
}
